### ISSUE TITLE
different experience from screenshot

### ISSUE THREAD

**Issue by Javid-Izadfar** [siamak/atom-panda-syntax#5]
I have installed Panda as syntax and have Material UI as UI theme. My experience from using these two are way different from provided screenshots.

![capture](https://cloud.githubusercontent.com/assets/14288838/19809893/296474fe-9d38-11e6-81f3-a84692ba73e5.PNG)

these differences are not just bound to .js files.

**Comment by siamak** [comment]
@Javid-Izadfar Install [Babel-language](https://atom.io/packages/language-babel) package on atom.

**Comment by Javid-Izadfar** [comment]
Installed Babel-language and still not same:
![js](https://cloud.githubusercontent.com/assets/14288838/19811564/c813f8b2-9d3e-11e6-852a-28e4d6c815b1.PNG)

An as I mentioned before, these differences are not just about js files.

on html (mind the double quotations):
![html](https://cloud.githubusercontent.com/assets/14288838/19811661/42b206ea-9d3f-11e6-85de-141b3c2b14a3.PNG)

on scss:
![scss](https://cloud.githubusercontent.com/assets/14288838/19811692/5afe13a6-9d3f-11e6-817f-23f111c417c3.PNG)

and Gods know where else!

**Comment by siamak** [comment]
@Javid-Izadfar Your screenshots for new version of Panda. _Screen shots in repo are for first release_! I should update them 🙏🏻
