### ISSUE TITLE
Atom Syntax Selectors Changed in v1.3

### ISSUE THREAD

**Issue by dhedgecock** [siamak/atom-panda-syntax#6]
Hello, it looks like Atom has removed the shadow DOM in v1.3 and syntax packages have to change their css selectors.

If you'd like I can make a PR with these updates.

<img width="1157" alt="screen shot 2017-01-12 at 7 10 33 am" src="https://cloud.githubusercontent.com/assets/8461733/21895095/51fb08c6-d896-11e6-8311-413197a244c8.png">

**Comment by siamak** [comment]
@DHedgecock Hi. Thanks for Report this bug. Today i'm busy. please make a PR with these updates. Thanks 👍

**Comment by siamak** [comment]
@DHedgecock I published new version of Panda on `apm`.
![image](https://cloud.githubusercontent.com/assets/3109082/21904098/c220b728-d917-11e6-9fb8-8766a78892f5.png)

**Comment by dhedgecock** [comment]
NICE 👍 

By the way this is the best theme I've ever had. Thanks for all the time you've put into it.
