### ISSUE TITLE
Deprecated selector in `atom-panda-syntax/index.less`

### ISSUE THREAD

**Issue by ashkanRmk** [siamak/atom-panda-syntax#7]
In `atom-panda-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--entity.syntax--name.syntax--function,
.entity.syntax--name.syntax--function` => `.syntax--entity.syntax--name.syntax--function,
.syntax--entity.syntax--name.syntax--function`

* `.syntax--entity.syntax--name.syntax--type,
.entity.syntax--name.syntax--type` => `.syntax--entity.syntax--name.syntax--type,
.syntax--entity.syntax--name.syntax--type`

* `.syntax--entity.syntax--other.syntax--inherited-class,
.entity.syntax--other.syntax--inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class,
.syntax--entity.syntax--other.syntax--inherited-class`

* `.syntax--entity.syntax--name.syntax--class,
.entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class,
.entity.syntax--name.syntax--type.syntax--class` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.syntax--entity.syntax--name.syntax--section,
.entity.syntax--name.syntax--section` => `.syntax--entity.syntax--name.syntax--section,
.syntax--entity.syntax--name.syntax--section`

* `.syntax--entity.syntax--name.syntax--tag,
.entity.syntax--name.syntax--tag` => `.syntax--entity.syntax--name.syntax--tag,
.syntax--entity.syntax--name.syntax--tag`

* `.syntax--entity.syntax--other.syntax--attribute-name,
.entity.syntax--other.syntax--attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name,
.syntax--entity.syntax--other.syntax--attribute-name`

* `.syntax--entity.syntax--other.syntax--attribute-name.syntax--placeholder,
.entity.syntax--other.syntax--attribute-name.syntax--placeholder` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--placeholder,
.syntax--entity.syntax--other.syntax--attribute-name.syntax--placeholder`

* `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id,
.entity.syntax--other.syntax--attribute-name.syntax--id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id,
.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by siamak** [comment]
@Ashkan-rmk `v.0.18.0` Released on apm. Thanks 👍
